name: scraper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
   - cron: "*/40 * * * *"

jobs:
  import-data:
    runs-on: ubuntu-latest

    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::rvest
            any::glue
            any::stringr
            any::jsonlite
            any::lubridate
            any::curl

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript script.R

      - name: Set Workflow A Status
        run: echo "success" > success.txt

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
